% construction of gama matrices at finest level
function mgh = compute_gamma_matrices(mgh)

  block_size = 12/4;
  I = speye(block_size);
  zero = sparse(block_size,block_size);

  dim4D = nthroot( size(mgh.D{1},1)/12,4 );
  size3D = size(mgh.D{1},1)/dim4D;
  nr_sites = size3D/12;

  mgh.gs{1} = kron(speye(nr_sites), ...
               [zero,  zero,  zero, 1i*I;...
                zero,  zero,  1i*I, zero;...
                zero,  -1i*I, zero, zero; ...
                -1i*I, zero,  zero, zero]);
  mgh.gs{2} = kron(speye(nr_sites),...
               [zero,  zero,  zero, -I;  ...
                zero,  zero,  I,    zero;...
                zero,  I,     zero, zero; ...
                -I,    zero,  zero, zero]);
  mgh.gs{3} = kron(speye(nr_sites), ... 
               [zero, zero, 1i*I, zero;...
                zero, zero, zero, -1i*I;...
               -1i*I, zero, zero, zero; ...
                zero, 1i*I, zero, zero]);
  mgh.gs{4} = kron(speye(nr_sites), ... 
               [zero, zero, I,    zero; ...
                zero, zero, zero, I;    ...
                I,    zero, zero, zero; ...
                zero, I,    zero, zero]);
end